import { Platform } from 'react-native';

export default {
  // COLOURS
  white: '#ffffff',
  'black-100': '#000000',
  'black-80': '#5c5c5c',
  'black-60': '#666666',
  pinkText: '#d22d7d',
  orangeText: '#d63f15',
  yellowText: '#a9660e',
  greenText: '#1d8657',
  blueText: '#157eaa',
  purpleText: '#696eb4',
  pinkBg: '#d22d7d',
  orangeBg: '#f05023',
  yellowBg: '#fa9b1e',
  greenBg: '#28af73',
  blueBg: '#28aae1',
  purpleBg: '#696eb4',

  // TYPEFACES
  fontPrimary: 'Times New Roman',
  fontSecondary: 'Arial',
  whiteButton: {
    height: 40,
    margin: 10,
    marginRight: 100,
    marginLeft: 100,
    padding: 10,
    alignSelf: 'stretch',
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    borderColor: '#666666',
    borderWidth: 1,
    borderStyle: 'solid',
  },
  whiteButtonText: {
    fontSize: Platform.OS === 'ios' ? 16 : 20,
    color: '#157eaa',
  },
  blueButton: {
    height: 40,
    margin: 10,
    marginRight: 100,
    marginLeft: 100,
    padding: 10,
    alignSelf: 'stretch',
    backgroundColor: '#28aae1',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
  },
  blueButtonText: {
    fontSize: Platform.OS === 'ios' ? 16 : 20,
    color: '#ffffff',
  },
};
